# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb944c0129eb04b7de0390c144f7e67e68773e8a9e86a1d212e924fd3fd4800724064637f30f97c9eb5fe01cb053147140ea5db4b49e4834100c370ed6e24cb2

test:
  secret_key_base: ae2de7815e6995ee166ff4086864416dc2cad918c3763d8a51e0f1485f5fc4d6efbf98035e4e364f87b1b457bb07af174e3f57ee20df2106c0d825638d863eff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
